In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.style as style
import seaborn as sns

# Regression

<img src= "https://www.tibco.com/sites/tibco/files/media_entity/2020-09/regression-analysis-diagram.svg" alt ="Regression" style='width: 800px;'>

In [2]:
bitcoin=pd.read_csv("../input/cryptocurrencypricehistory/coin_Bitcoin.csv")
HF=pd.read_csv("../input/heart-failure-clinical-data/heart_failure_clinical_records_dataset.csv")

In [3]:
pd.set_option('display.max_columns', None)
bitcoin.head()

SNo     Name Symbol                 Date        High         Low  \
0    1  Bitcoin    BTC  2013-04-29 23:59:59  147.488007  134.000000   
1    2  Bitcoin    BTC  2013-04-30 23:59:59  146.929993  134.050003   
2    3  Bitcoin    BTC  2013-05-01 23:59:59  139.889999  107.720001   
3    4  Bitcoin    BTC  2013-05-02 23:59:59  125.599998   92.281898   
4    5  Bitcoin    BTC  2013-05-03 23:59:59  108.127998   79.099998   

         Open       Close  Volume     Marketcap  
0  134.444000  144.539993     0.0  1.603769e+09  
1  144.000000  139.000000     0.0  1.542813e+09  
2  139.000000  116.989998     0.0  1.298955e+09  
3  116.379997  105.209999     0.0  1.168517e+09  
4  106.250000   97.750000     0.0  1.085995e+09

In [4]:
bitcoin.shape

(2991, 10)

In [5]:
bitcoin.Name.unique()

array(['Bitcoin'], dtype=object)

In [6]:
bitcoin.Symbol.unique()

array(['BTC'], dtype=object)

In [7]:
bitcoin.drop(["Name"],axis=1, inplace=True)

In [8]:
bitcoin.drop(["SNo"],axis=1, inplace=True)

In [9]:
bitcoin.drop(["Symbol"],axis=1, inplace=True)

In [10]:
bitcoin.columns

Index(['Date', 'High', 'Low', 'Open', 'Close', 'Volume', 'Marketcap'], dtype='object')

In [11]:
HF.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [12]:
HF.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [13]:
HF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [14]:
bitcoin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2991 entries, 0 to 2990
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       2991 non-null   object 
 1   High       2991 non-null   float64
 2   Low        2991 non-null   float64
 3   Open       2991 non-null   float64
 4   Close      2991 non-null   float64
 5   Volume     2991 non-null   float64
 6   Marketcap  2991 non-null   float64
dtypes: float64(6), object(1)
memory usage: 163.7+ KB


In [15]:
bitcoin.describe()

High           Low          Open         Close        Volume  \
count   2991.000000   2991.000000   2991.000000   2991.000000  2.991000e+03   
mean    6893.326038   6486.009539   6700.146240   6711.290443  1.090633e+10   
std    11642.832456  10869.032130  11288.043736  11298.141921  1.888895e+10   
min       74.561096     65.526001     68.504997     68.431000  0.000000e+00   
25%      436.179001    422.879486    430.445496    430.569489  3.036725e+07   
50%     2387.610107   2178.500000   2269.889893   2286.409912  9.460360e+08   
75%     8733.926948   8289.800459   8569.656494   8576.238715  1.592015e+10   
max    64863.098908  62208.964366  63523.754869  63503.457930  3.509679e+11   

          Marketcap  
count  2.991000e+03  
mean   1.208761e+11  
std    2.109438e+11  
min    7.784112e+08  
25%    6.305579e+09  
50%    3.741503e+10  
75%    1.499957e+11  
max    1.186364e+12

In [16]:
import datetime as dt
bitcoin["Date"]=pd.to_datetime(bitcoin["Date"])
bitcoin['Date_year'] = bitcoin["Date"].dt.year
bitcoin['Date_month'] = bitcoin["Date"].dt.month
bitcoin['Date_day'] = bitcoin["Date"].dt.day
bitcoin['Date_hour'] = bitcoin["Date"].dt.hour
bitcoin['Date_minute'] = bitcoin["Date"].dt.minute
bitcoin['Date_seconde'] = bitcoin["Date"].dt.second


In [17]:
bitcoin.drop(["Date"], axis=1, inplace=True)

In [18]:
bitcoin.head()

High         Low        Open       Close  Volume     Marketcap  \
0  147.488007  134.000000  134.444000  144.539993     0.0  1.603769e+09   
1  146.929993  134.050003  144.000000  139.000000     0.0  1.542813e+09   
2  139.889999  107.720001  139.000000  116.989998     0.0  1.298955e+09   
3  125.599998   92.281898  116.379997  105.209999     0.0  1.168517e+09   
4  108.127998   79.099998  106.250000   97.750000     0.0  1.085995e+09   

   Date_year  Date_month  Date_day  Date_hour  Date_minute  Date_seconde  
0       2013           4        29         23           59            59  
1       2013           4        30         23           59            59  
2       2013           5         1         23           59            59  
3       2013           5         2         23           59            59  
4       2013           5         3         23           59            59

In [19]:
X=bitcoin.drop(["Marketcap"], axis=1)
Y=bitcoin["Marketcap"]
X.head()

High         Low        Open       Close  Volume  Date_year  \
0  147.488007  134.000000  134.444000  144.539993     0.0       2013   
1  146.929993  134.050003  144.000000  139.000000     0.0       2013   
2  139.889999  107.720001  139.000000  116.989998     0.0       2013   
3  125.599998   92.281898  116.379997  105.209999     0.0       2013   
4  108.127998   79.099998  106.250000   97.750000     0.0       2013   

   Date_month  Date_day  Date_hour  Date_minute  Date_seconde  
0           4        29         23           59            59  
1           4        30         23           59            59  
2           5         1         23           59            59  
3           5         2         23           59            59  
4           5         3         23           59            59

In [20]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()



In [21]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

In [22]:
LR.fit(xtrain,ytrain)

LinearRegression()

In [23]:
ypred=LR.predict(xtest)

In [24]:
ypred

array([3.04339045e+11, 1.96749196e+11, 1.27657690e+11, 8.55502648e+09,
       1.84586852e+11, 9.97291083e+10, 6.97108166e+11, 8.69927405e+08,
       5.99239388e+09, 6.23249133e+11, 9.30426026e+10, 1.09287619e+11,
       7.04736035e+11, 1.46532434e+11, 6.42830250e+09, 5.65944503e+10,
       6.43196166e+09, 9.10024779e+08, 1.78716934e+11, 1.85433527e+11,
       4.56529816e+08, 1.75769900e+11, 9.53184252e+09, 5.99020974e+11,
       1.73939451e+09, 3.95599571e+09, 2.36945727e+11, 5.44466811e+08,
       2.52771360e+11, 2.09627314e+11, 5.91585131e+08, 3.35666879e+11,
       2.57005703e+11, 9.20060288e+09, 1.60466381e+09, 9.47162741e+09,
       6.54190164e+10, 4.42176021e+08, 1.68333101e+11, 3.59574734e+09,
       1.28977425e+11, 7.27874469e+11, 6.24203241e+08, 1.06943058e+12,
       8.44508714e+09, 2.94924890e+09, 9.24785555e+10, 4.12086363e+10,
       1.60177927e+11, 3.93199239e+09, 1.48163205e+11, 3.22873789e+09,
       1.48130734e+11, 1.33726407e+11, 7.36950092e+08, 1.63061721e+10,
      

In [25]:
print(pd.DataFrame({'real_value':ytest,'pred_value':ypred}))

        real_value    pred_value
1690  2.773103e+11  3.043390e+11
2706  1.978100e+11  1.967492e+11
1951  1.240446e+11  1.276577e+11
458   7.670841e+09  8.555026e+09
2311  1.823255e+11  1.845869e+11
...            ...           ...
1377  1.683741e+10  1.391182e+10
198   4.883103e+09  5.735979e+09
2977  6.320113e+11  6.222758e+11
1810  1.340430e+11  1.415056e+11
1227  9.743676e+09  6.428349e+09

[599 rows x 2 columns]


In [26]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)


3050924904.938302

In [27]:
LR.score(xtest,ytest)

0.9994421696573469

# Lasso Regression



<img src= "https://i.ytimg.com/vi/NGf0voTMlcs/maxresdefault.jpg" alt ="Lasso " style='width: 800px;'>

In [28]:
from sklearn.linear_model import Lasso
Ls=Lasso()
Ls.fit(xtrain,ytrain)
ypred=Ls.predict(xtest)
Ls.score(xtest,ytest)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:531: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.4008853745049105e+22, tolerance: 1.117938737863933e+22
  positive)


0.9992343600424525

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

3462926078.2266183

# DECISION TREE REGRESSION 

<img src= "https://www.saedsayad.com/images/Decision_tree_r1.png" alt ="" style='width: 800px;'>

In [30]:
from sklearn.tree import DecisionTreeRegressor
mytre=DecisionTreeRegressor(max_depth=1)
mytre.fit(xtrain,ytrain)
ypredd=mytre.predict(xtest)
mytre.score(xtest,ytest)

0.7691704644820736

here we see the difference between the two model when we play with their params

In [31]:
from sklearn.tree import DecisionTreeRegressor
mytre=DecisionTreeRegressor(max_depth=5)
mytre.fit(xtrain,ytrain)
ypredd=mytre.predict(xtest)
mytre.score(xtest,ytest)

0.997896237921588

In [32]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypredd)

5077785411.153317

# Classification

![](https://csharpcorner-mindcrackerinc.netdna-ssl.com/article/a-quick-overview-of-machine-learning-tasks/Images/Classification%20in%20Machine%20learning.JPG)

In [33]:
HF.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [34]:
x=HF.drop(["DEATH_EVENT"], axis=1)
y=HF["DEATH_EVENT"]

In [35]:
x.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time'],
      dtype='object')

In [36]:
x.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
dtype: int64

##### 

In [37]:
y.isnull().sum()

0

In [38]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
dtypes: float64(3), int64(9)
memory usage: 28.2 KB


In [39]:
x.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  
count         299.00000    299.000000  299.000000  299.00000  299.000000  
mean            1.39388    136.625418    0.648829    0.32107  130.260870  
std             1.03451      4.412477    0.478136    0.46767   77.614208  
min             0.50000    113.000000    0.000000    0.00000    4.000000  
25%             0.90000    134.000000    0.000000    0.00000   73.000000  
50%             1.10000    137.000000    1.000000    0.00000  115.000000  
75%             1.40000    140.000000    1.000000    1.00000  203.000000  
max             9.40000    148.000000    1.000000    1.00000  285.000000

In [40]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

# Support Vector Machines

![](https://static.javatpoint.com/tutorial/machine-learning/images/support-vector-machine-algorithm.png)

In [41]:
from sklearn import svm
svm= svm.SVC()
svm.fit(xtrain,ytrain)

SVC()

In [42]:
ypred=svm.predict(xtest)

In [43]:
svm.score(xtest,ytest)

0.7

In [44]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

0.3

# Logistic Regression

![](https://static.javatpoint.com/tutorial/machine-learning/images/linear-regression-vs-logistic-regression.png)

In [45]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [46]:
from sklearn.linear_model import LogisticRegression
LGR=LogisticRegression()


In [47]:
LGR.fit(xtrain,ytrain)

LogisticRegression()

In [48]:
ypred=LGR.predict(xtest)

In [49]:
LGR.score(xtest,ytest)

0.8166666666666667

In [50]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

0.18333333333333332

# KNeighborsClassifier

![](https://static.javatpoint.com/tutorial/machine-learning/images/k-nearest-neighbor-algorithm-for-machine-learning2.png)

In [51]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier()
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

In [52]:
KNN.predict(xtest)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
KNN.score(xtest,ytest)

0.6833333333333333

# Naive Bayes

![](https://www.astroml.org/_images/fig_simple_naivebayes_1.png)

In [54]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
ypred = gnb.fit(xtrain, ytrain).predict(xtest)
ypred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [55]:
gnb.score(xtest,ytest)

0.8

In [56]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

0.2

# DecisionTreeClassifier

![](https://miro.medium.com/max/1200/1*xGsYc6aXehD7lyoLEn-mMA.png)

In [57]:
from sklearn.tree import DecisionTreeClassifier
mytree=DecisionTreeClassifier(max_depth=8)
mytree.fit(xtrain,ytrain)
ypred=mytree.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [58]:
mytree.score(xtest,ytest)

0.7333333333333333

In [59]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

0.26666666666666666

# ExtraTreeClassifier

![](https://sigopt.com/wp-content/uploads/2018/10/majority-weighted-voting.png)

In [60]:
from sklearn.tree import ExtraTreeClassifier
extree=ExtraTreeClassifier()
extree.fit(xtrain,ytrain)
ypred=extree.predict(xtest)
ypred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1])

In [61]:
extree.score(xtest,ytest)

0.7333333333333333

In [62]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest, ypred)

0.26666666666666666